name = "notecleaner"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output"

[env.production.vars]
ENVIRONMENT = "production"
NEXT_PUBLIC_PAYPAL_CLIENT_ID = "your-paypal-client-id-here"
